name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test sigplot-bitarray
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.2.0
      with:
        version: "v0.9.1"
    - name: Run tests in headless Firefox
      run: wasm-pack test --headless --firefox
    - name: Run tests in headless Chrome
      run: wasm-pack test --headless --chrome
